name: Update Submodules on Commit

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Classroom Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
          
      - name: Checkout Submodules
        run: |
          git submodule update --init --recursive

      - name: Update Submodules
        run: |
          git submodule update --recursive --remote

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Updated submodules" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/justin-prabhakaran/aaaclass.git main
