name: Update Submodules

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  update_submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Classroom Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          submodules: recursive

      - name: Update Submodules
        run: |
          git submodule update --init --recursive --remote

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "noreply@github.com"
          git add .
          git commit -m "Updated submodules from frontend and backend" || echo "No changes to commit"

      - name: Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git push origin main
